### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by puppykickr** [igrmk/smsq#1]
Tried using the app.
Followed the basically nonexistant  instructions.

Texts are not forwarded to Telegram.

Tried with two different numbers, devices, and Telegram channels.

The app does not work.

**Comment by igrmk** [comment]
Could you please be more specific on what you did. I'm quite confused how you managed to add it to a channel. If you just downloaded and installed the application then after you press "START" and "CONNECT TELEGRAM" you are forwarded to Telegram bot smsq_bot. You press the only button "START" in Telegram and that is it.

The bot is intended for personal use due to privacy concerns. It should state this if you add it to a group. Probably I need to check channels as well.

**Comment by puppykickr** [comment]
I have two Telegram channels.
The bot appeared on the channels, although only on one channel at a time.

But no texts were ever forwarded to Telegram on either channel.

**Comment by igrmk** [comment]
@puppykickr Thank you for your explanation!
However the bot is not intended for using in a channel or a group.
The main reasons are privacy and security concerns.
Now the bot reports it explicitly if you try to use it in a group or a channel.
Here is the change https://github.com/igrmk/smsq/commit/de57f13c55330b75900cced3eba9ae63bdf0f531
